### ISSUE TITLE
Add link to JOSS paper

### ISSUE THREAD

**Issue by pdebuyl** [simonrp84/PyCoxMunk#14]
Seems like a nice addition for the README and for the docs :-)

**Comment by simon-sat** [comment]
Whoa, I'd forgotten about this repo! Thanks for the idea, have now added a link in both the docs + readme.

**Comment by pdebuyl** [comment]
Well, this is the purpose of JOSS :-)

(I was checking it out for the case of having sample data and couldn't find the link to the paper)
